<?php
$pageTitle = 'Register';
$this->headTitle($pageTitle);
?>
    <h1><?= $this->escapeHtml($pageTitle) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$fname = $form->get('first_name');
$fname->setAttribute('class', 'form-control');
$fname->setAttribute('placeholder', 'First name');


$lname = $form->get('last_name');
$lname->setAttribute('class', 'form-control');
$lname->setAttribute('placeholder', 'Last name');

// This provides a default CSS class and placeholder text for the artist element:
$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'email');

// This provides a default CSS class and placeholder text for the artist element:
$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'password');

// This provides a default CSS class and placeholder text for the artist element:
$repeat_password = $form->get('repeat_password');
$repeat_password->setAttribute('class', 'form-control');
$repeat_password->setAttribute('placeholder', 'Repeat password');


// This provides a default CSS class and placeholder text for the artist element:
$phone = $form->get('phone');
$phone->setAttribute('class', 'form-control');
$phone->setAttribute('placeholder', 'Phone number:: Only numbers, - and /');


// This provides a default CSS class and placeholder text for the artist element:
$photo = $form->get('photo');
$photo->setAttribute('class', 'form-control');
$photo->setAttribute('placeholder', 'Your Avatar photo');



// This provides a default CSS class and placeholder text for the artist element:
$captcha = $form->get('captcha');
$captcha->setAttribute('class', 'form-control');
$captcha->setAttribute('placeholder', 'Captcha');



// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($fname) ?>
        <?= $this->formElement($fname) ?>
        <?= $this->formElementErrors()->render($fname, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($lname) ?>
        <?= $this->formElement($lname) ?>
        <?= $this->formElementErrors()->render($lname, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($email) ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($password) ?>
        <?= $this->formElement($password) ?>
        <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($repeat_password) ?>
        <?= $this->formElement($repeat_password) ?>
        <?= $this->formElementErrors()->render($repeat_password, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($phone) ?>
        <?= $this->formElement($phone) ?>
        <?= $this->formElementErrors()->render($phone, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($photo) ?>
        <?= $this->formElement($photo) ?>
        <?= $this->formElementErrors()->render($photo, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($captcha) ?>
        <?= $this->formElement($captcha) ?>
        <?= $this->formElementErrors()->render($captcha, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();