<?php
echo $this->flashMessenger()->render();
$pageTitle = 'Login';
$this->headTitle($pageTitle);
?>
    <h1><?= $this->escapeHtml($pageTitle) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the artist element:
$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'email');

// This provides a default CSS class and placeholder text for the artist element:
$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'password');


// This provides a default CSS class and placeholder text for the artist element:
$captcha = $form->get('captcha');
$captcha->setAttribute('class', 'form-control');
$captcha->setAttribute('placeholder', 'Captcha');



// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', ['action' => 'login']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>

    <div class="form-group">
        <?= $this->formLabel($email) ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($password) ?>
        <?= $this->formElement($password) ?>
        <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
    </div>


    <div class="form-group">
        <?= $this->formLabel($captcha) ?>
        <?= $this->formElement($captcha) ?>
        <?= $this->formElementErrors()->render($captcha, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('csrf'));
echo $this->form()->closeTag();