<?php

$title = 'Profile of '.ucfirst($user['first_name']).' '.ucfirst($user['last_name']);

$this->headTitle($title);
?>
<h1><?= $title ?></h1>

<table class="table">
    <tr>
        <td>First name</td>
        <td>Last name</td>
        <td>Email</td>
        <td>Phone</td>
        <td>Create date</td>
    </tr>
    <?php

        ?>
    <tr>
        <td><?= $user['first_name'] ?></td>
        <td><?= $user['last_name'] ?></td>
        <td><?= $user['email'] ?></td>
        <td><?= $user['phone'] ?></td>
        <td><?= $user['created'] ?></td>
    </tr>
    <?php
    ?>
</table>

